version: '3'
services:
  web:
    image: anytask
    container_name: anytask
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=anytask.settings_docker
    restart: always
    volumes:
      - ../../anytask-data:/app/data

networks:
  default:
    external:
        name: $NETWORK